[deps]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
ExactPenalty = "9416bf39-c24a-5b52-a5c2-6dfe9a752fef"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
RegularizedOptimization = "20620ad1-4fe4-4467-ae46-fb087718fe7b"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"
