[deps]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExactPenalty = "9416bf39-c24a-5b52-a5c2-6dfe9a752fef"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RegularizedOptimization = "20620ad1-4fe4-4467-ae46-fb087718fe7b"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"

[sources]
ExactPenalty = {path = ".."}
