name = "ExactPenalty"
uuid = "9416bf39-c24a-5b52-a5c2-6dfe9a752fef"
version = "0.1.0"
authors = ["Maxence Gollier maxence-2.gollier@polymtl.ca"]

[deps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
QRMumps = "422b30a1-cc69-4d85-abe7-cc07b540c444"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegularizedOptimization = "20620ad1-4fe4-4467-ae46-fb087718fe7b"
RegularizedProblems = "ea076b23-609f-44d2-bb12-a4ae45328278"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"

[compat]
CUTEst = "1.3.6"
Krylov = "0.10"
LinearAlgebra = "1.10"
LinearOperators = "2.10.0"
NLPModels = "0.20, 0.21, 0.22"
NLPModelsModifiers = "0.7.2"
ProximalOperators = "0.15.3"
QRMumps = "0.3.2"
Random = "1.10.0"
RegularizedOptimization = "0.2.0"
RegularizedProblems = "0.1.1"
ShiftedProximalOperators = "0.2.3"
SolverCore = "0.3.8"
SparseMatricesCOO = "0.2.4"
julia = "^1.6.0"

[extras]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CUTEst", "Test"]
